### ISSUE TITLE
DetourRestoreAfterWIth() cannot be used

### ISSUE THREAD

**Issue by asava** [wbenny/DetoursNT#1]
Hello,

Nice work.

However I have an issue:
DetourRestoreAfterWith(); cannot be used, it results in:
LNK2019	unresolved external symbol DetourRestoreAfterWith referenced in function "int __cdecl NtDllMain(struct HINSTANCE__ *,unsigned long,void *)" (?NtDllMain@@YAHPEAUHINSTANCE__@@KPEAX@Z)

**Comment by wbenny** [comment]
Hi,

thank you and yes, this is because Detours/src/modules.cpp is not included in the DetoursNT project. I left it out because:
- it contains advanced methods which are not crucial for hooking itself
- it would require to mock additional functions
- if anyone needs to use DetourCreateProcessWithDllEx or DetourCreateProcessWithDlls (which are related to DetourRestoreAfterWith), having NTDLL-only detours is pointless anyway

**Comment by asava** [comment]
Hello,

I understand. However NTDLL-only hooking can bring advantages even to more advances cases, even if only by reducing dependencies, which can help in some cases. But I do realize it would require more work. 

Another (related) issue, I see that creatwth.cpp is also not included (MyDetourFinishHelperProcess from there is often exported as ordinal #1).

**Comment by wbenny** [comment]
Yes, that is left out on purpose as well for exact same reasons. As stated in the readme, the main benefit of NTDLL-only Detours is that it can be used either for native processes and/or used to hook process in a very early stage. Neither of that is achievable with modules.cpp nor creatwith.cpp.

If you want to use any functions from module.cpp or creatwth.cpp, I can't see any benefit which could "NTDLL-only dependency" bring and I would suggest using just original Detours with all its dependencies. In fact, supporting it would cause unnecessary bloating and reimplementing of functions which already are in KERNEL32.DLL.

Although if you or anyone else take the time and make it work, I am open to accept a pull request.
